name: Test
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  py-compile:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner.
      - name: Compile
        uses: TwilightWings/PyCompile@main
        with:
          filename: 'input.py'
      - name: execute commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Python Compile crongenerated"
          git push
